### ISSUE TITLE
wph_moments_indices

### ISSUE THREAD

**Issue by NiallJeffrey** [bregaldo/pywph#4]
When I run wph_op.wph_moments_indices(), I get a shape that doesn't match the coefficients returns by wph_op.apply().

Is this the desired behaviour?

**Comment by bregaldo** [comment]
This discrepancy should coincide with the number of scaling moments estimates ("L" class of moments).

You can check that the combination of wph_op.scaling_moments_indices and wph_op.wph_moments_indices gives you a consistent number of coefficients with what is returned by the apply method.
